"""added autogenerated relation

Revision ID: 2f10d65e5ec3
Revises: dc4314ba8647
Create Date: 2023-01-24 16:04:48.728908

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f10d65e5ec3'
down_revision = 'dc4314ba8647'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'weight',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_index(op.f('ix_products_product_name'), 'products', ['product_name'], unique=False)
    op.create_foreign_key(None, 'products', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_product_name'), table_name='products')
    op.alter_column('products', 'weight',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
